[messages]
no_permission = "&cYou don't have permission to use this command."
usage_ban = "&eUsage: /ban <player> <time (1d, 1w, 1m, 1y)> <reason>"
usage_unban = "&eUsage: /unban <player>"
usage_checkban = "&eUsage: /checkban <player>"
checkban = "&4&m-----&4[ &cPurgatory &4]&m-----\n&cUser: &f%player% &c(ID: &f%id%&c)\n&cBanned: &f%blacklisted%\n&cReason: &f%reason%\n&cStaff: &f%staff%\n&cTime: &f%time%\n&4&m---------------------------"
player_not_found = "&cPlayer not found."
player_banned = "&aPlayer %player% has been banned for: %reason%"
player_disconnected = "&cYou have been banned: %reason%"
player_unbanned = "&aPlayer has been unbanned."
player_not_banned = "&cPlayer is not banned."
invalid_uuid = "&cInvalid UUID format."
ban_message_when_online = "&cYou are still banned for: %reason%\n&cTime remaining: %time%"

# Permissions
[permissions]
manager = "ocnw.manager"

[mysql]
enabled = false
ip = "ip:3306"
username = "username"
password = "password"
database = "database"

[purgatory]
server = "purgatory"
hub = "hub"